"""Add Phone Number

Revision ID: 970061bc2f55
Revises: fa635fdcfd20
Create Date: 2025-01-23 08:24:17.986466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970061bc2f55'
down_revision: Union[str, None] = 'fa635fdcfd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'phone_number')
    # ### end Alembic commands ###
