"""auto-vote

Revision ID: fa635fdcfd20
Revises: 2e34d4fcc13a
Create Date: 2025-01-23 08:19:27.875414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa635fdcfd20'
down_revision: Union[str, None] = '2e34d4fcc13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('Posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_Posts_id'), 'Posts', ['id'], unique=False)
    op.create_index(op.f('ix_Posts_title'), 'Posts', ['title'], unique=False)
    op.add_column('Users', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_column('Users', 'name')
    op.drop_index(op.f('ix_Posts_title'), table_name='Posts')
    op.drop_index(op.f('ix_Posts_id'), table_name='Posts')
    op.alter_column('Posts', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('Votes')
    # ### end Alembic commands ###
